### ISSUE TITLE
Error in table issue

### ISSUE THREAD

**Issue by shomitcse** [dem123456789/Library-Management-System#1]
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(ISBN,CopyID)),
FOREIGN KEY (Username) REFERENCES STUDENT_FACULTY(Username) ON D'

**Comment by diaoenmao** [comment]
Sorry, I no longer maintain this repo. This repo is just for reference.
